# Generated by Django 6.0.2 on 2026-02-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ingredient_options_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient'], 'verbose_name': 'recipe ingredient', 'verbose_name_plural': 'recipe ingredients'},
        ),
    ]
